project:
  type: website
  render:
    - "index.qmd"
    - "positron/*.qmd"
    - "pkg-dev/*.qmd"
    - "slides/*.qmd"

website:
  title: "RaukR 2026"
  page-navigation: true
  site-url: https://jennybc.github.io/2026_raukr-positron-ai-pkg-dev/
  repo-url: https://github.com/jennybc/2026_raukr-positron-ai-pkg-dev
  sidebar:
    id: main
    title: "RaukR 2026"
    pinned: true
    align: center
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - text: "---"
      - href: positron/index.qmd
        text: "Positron and Posit Assistant"
      - section: "Package development"
        href: pkg-dev/index.qmd
        contents:
          - pkg-dev/01-setup.qmd
          - pkg-dev/02-create-pkg-and-metadata.qmd
          - pkg-dev/03-documentation.qmd
          - pkg-dev/04-testing.qmd
          - pkg-dev/05-dependencies.qmd
          - pkg-dev/06-ci.qmd
          - pkg-dev/07-website.qmd
          - pkg-dev/08-share.qmd
  page-footer:
    left: |
      Content by Jenny Bryan, licensed
      [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)
    center:
      - icon: github
        href: https://github.com/jennybc/2026_raukr-positron-ai-pkg-dev
        aria-label: Source repository on GitHub
    right: |
      Made with [Quarto](https://quarto.org/)

format:
  html:
    theme: [zephyr, footer.scss]
    toc: true
